### ISSUE TITLE
Category Module || Category modification successful message issue 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#100]
Scenario :   

1) Click on Edit button of any category to do some changes
2) Update some information and click on modify button.

Actual result : When I click on Modify button no successful message is appearing but in actual modification is happening ,due to which admin gets whether changes has been made or not.

Expected result : when user click on modify button, "Category updated successfully" pop up should appear

**Comment by ameyranavade** [comment]
Request URL: http://api.shivajimaharaj.in/api/Admin/MasterManagement/Category

{"Ref_Category_ID":9,"Ref_Parent_ID":1,"CategoryName":"TEST 1312","AliasName":"test-1312","CategoryUseBy":0,"Description":"TESTINGss","MetaTitle":"","MetaKeywords":"","MetaDescription":"","IsActive":true,"Ref_User_ID":"5","FileManager":[],"Flag":"MODIFYCATEGORY","CreatedName":"amey ranavade"}

![image](https://user-images.githubusercontent.com/47138480/103141347-224a9600-4719-11eb-8117-f00612b64b69.png)

@RvThothwal Please check 500 error

**Comment by RvThothwal** [comment]
Done

**Comment by ameyranavade** [comment]
![image](https://user-images.githubusercontent.com/47138480/103157973-d95d1500-47de-11eb-93fd-ef45f67b3d71.png)
@RvThothwal new error msg

{"Flag":"ADDCATEGORY","Ref_Parent_ID":"1","Ref_Category_ID":"","CategoryName":"delete this","AliasName":"delete-this","Description":"123","CategoryUseBy":"1","FileUrls":[],"Ref_User_ID":"5","CreatedName":"amey ranavade","MetaTitle":"1","MetaKeywords":"1","MetaDescription":"1"}
