### ISSUE TITLE
Category module || Edit / delete / view button layout change 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#102]
In category module :
Kindly change the design of Edit / Delete / View button as per the attached file 

**Note : Before changing this you can discuss once with Pragnesh/ Eden / Akash**

PFA
![Expected buttons](https://user-images.githubusercontent.com/69690962/102015365-41444200-3d81-11eb-8c1d-eea32310ddca.jpg)

**Comment by pagumakwana** [comment]
View button is not required in gener module.
resolved

**Comment by sangeetajad** [comment]
as discussed with pragnesh, current buttons are proper hence closing this
