### ISSUE TITLE
Service Module || In service module - Category list issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#103]
In Service Module  :  

1) At service list page , click on "Select category" drop down, there only one category is displaying
2) In Add service page as well in "Select category " drop down only one category is displaying

But In actual , category module there are multiple categories available ... Infect I have added new category as well but those categories are not available in SERVICE  module , in category list

Expected result : All the added categories should be present in the Service module Category selection drop down

PFA

![Select category 1](https://user-images.githubusercontent.com/69690962/102015730-502bf400-3d83-11eb-8db0-0fa81dbddd23.png)
![select category 2](https://user-images.githubusercontent.com/69690962/102015732-515d2100-3d83-11eb-9b5d-3d5815b32e1f.png)
![mutiple category in category module](https://user-images.githubusercontent.com/69690962/102015744-5f12a680-3d83-11eb-8abe-803170fd5713.png)

**Comment by ameyranavade** [comment]
Made necessary changes
