### ISSUE TITLE
Service Module || Service cover image issues

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#104]
Scenario :

1) I have added new service "TEST SERVICE 1312" with all the fields
2) When I check in service list , Thumbnail image (service cover image) is not visible also play button is not functional
3) Click on edit button, on modify page as well already browsed service video and image are not present, it is asking me to browse files again

Expected result : Added files should be visible at service list page as well as modify service page.

PFA

![service image n play functionality](https://user-images.githubusercontent.com/69690962/102016542-85d2dc00-3d87-11eb-99bb-7c2c4172293e.png)
![already added service files are not visible](https://user-images.githubusercontent.com/69690962/102016567-a13de700-3d87-11eb-88d0-4acddbb9812b.png)

**Comment by ameyranavade** [comment]
![image](https://user-images.githubusercontent.com/47138480/102710515-ece91700-42d8-11eb-9628-fa33cf0e60e7.png)

bheem Url doesnt contains Image

**Comment by RvThothwal** [comment]
Pragensh has changed the server and forgot to move images on new server.
