### ISSUE TITLE
Service module || Service entry count issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#106]
Scenario :   

1) for eg. there are 3 services available in the list , also page count as "showing 1 to 3 of 3 entries"
2) Now delete any service and then check count
it is still displaying "showing 1 to 3 of 3 entries"  instead of of "showing 1 to 2 of 2 entries"
I need to  revisit module to check updated page count

check after and before images attached.

![before deleting service count](https://user-images.githubusercontent.com/69690962/102093579-54214a00-3e47-11eb-84a2-d5ad4c852d7e.png)
![after deleting service](https://user-images.githubusercontent.com/69690962/102093611-5b485800-3e47-11eb-8c06-75faabf66590.png)

**Comment by ameyranavade** [comment]
@pagumakwana This is global issue need to do some RND as Datatable is not getting refreshed

**Comment by ameyranavade** [comment]
Made necessary changes
