### ISSUE TITLE
Track Module || Delete Track issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#108]
Scenario :  

1) Click on Delete button to delete any track

Actual result : Track gets deleted without giving any confirmation pop up

Expected result : While deleting any track when admin click on delete button then confirmation pop up should appear like "Are you sure you want to delete this Track?? "" with YES and CANCLE Button

**_Note : Please discuss with Pragnesh/Eden/Akash before implementing this delete functionality like whether they want to add any reason for deletion  or not??_**

**Comment by pagumakwana** [comment]
resolved
