### ISSUE TITLE
Track Module || Button designing

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#109]
As par attached screenshots ,
Kindly change layout of buttons (Approved / Rejected / Deleted / View / Edit)

**_Note : You can discuss with Pragnesh/ Eden / Akash before doing this changes_**

1) All track for Admin 

![All Tracks For Admin](https://user-images.githubusercontent.com/69690962/102231251-c65f6080-3f13-11eb-9114-28c24d3f85a5.png)

2) All track for producer

![All Tracks For Producer](https://user-images.githubusercontent.com/69690962/102231541-1807eb00-3f14-11eb-8f59-808f96669e87.jpg)

**Comment by PallaviChapla** [comment]
Iconic button done from my side. Developer has to call Iconic button design instead of the button. Let me if anyone need my help.

**Comment by smsan80** [comment]
Done
