### ISSUE TITLE
Beats Module || Detele issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#111]
1) Click on delete button, beat gets deleted without giving any pop up message

Expected result : When admin click on delete button , confirmation pop up should appear like "Are you sure you want to delete this Beat?? " with YES and CANCEL Button

Note :  Before implementing this you can discuss with Pragnesh/ Eden / Akash  whether they required any reason to gets added before deleting any beat.

**Comment by pagumakwana** [comment]
resolved
