### ISSUE TITLE
Tracks || Beats modules - Textual issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#112]
In tracks and beats module there is not consistency with Approved and Rejected text.

Make sure only 2 text should be displayed i.e "Approved" and "Rejected"

don't user word like "Approve  or Reject"

PFA

![in tracks textual issue](https://user-images.githubusercontent.com/69690962/102234430-49ce8100-3f17-11eb-820e-c88d6034972f.png)
![textual issue](https://user-images.githubusercontent.com/69690962/102234474-54891600-3f17-11eb-8381-9d7442637cff.png)

**Comment by pagumakwana** [comment]
Resolved
