### ISSUE TITLE
Frontend Tracks and Beats || Add to cart issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#113]
Whenever I click on Add to cart option of any Track or beat , nothing is happening
Also in MY CART list those tracks or beats are not present

In short Add to cart option is not functional

PFA

![add to cart is not functional in beats](https://user-images.githubusercontent.com/69690962/102238438-c6fbf500-3f1b-11eb-8140-b174e8c0c1be.png)
![add to cart is not functional in track](https://user-images.githubusercontent.com/69690962/102238445-c8c5b880-3f1b-11eb-85f4-413da8aefcac.png)

**Comment by ameyranavade** [comment]
@sangeetajad this is developed by santosh bhai

**Comment by smsan80** [comment]
Done
