### ISSUE TITLE
Manage category module || Mandatory field issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#15]
Scenario :
1) Direct click on  "Add" button. Mandatory field message is appearing only for "Enter category" and "Enter slug" field. But there is no * asterisk mark given.
2) I am able to add Category without selecting "Category type"

Expected result :  
1) Please add * asterisk mark before "Enter category" , "Enter slug" , "Select category type" fields.
2) Kindly show validation message for "Select category type" field as it should be a mandatory field.

PFA

![Mandatory field issue](https://user-images.githubusercontent.com/69690962/90307538-bc413d00-def4-11ea-8fc6-3aee3d61c186.png)

**Comment by ameyranavade** [comment]
Added * on required fields and also made Select category type as mandatory field.
