### ISSUE TITLE
Manage Category > delete button || Alignment issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#16]
Scenario :  
1)Go to  Manage Category
2) Click on the delete button of right hand side (Of any category)
3) As highlighted in screenshot, kindly fix alignment of "Cancel" and "Yes" button.

![alignment issue on cancel and yes button](https://user-images.githubusercontent.com/69690962/90307690-4047f480-def6-11ea-8d39-8c7b30c8aa72.png)

**Comment by PallaviChapla** [comment]
Done
