### ISSUE TITLE
Manage category > Add category || Textual issue 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#17]
Scenario : 

1) Whenever I enter any data with "Space bar" in "Enter category" field 
In "Enter slug" field instead of spaces "dash" is appearing

Expected result : 
Dash should not appear for "space entered"

![Space is reflecting as dash](https://user-images.githubusercontent.com/69690962/90307948-f0b6f800-def8-11ea-9599-cce40cbdf7be.png)

**Comment by ameyranavade** [comment]
Trim the value of slug before saving. also hide the slug field as discussed with @pagumakwana
