### ISSUE TITLE
Manage Category > Add Category || Able to edit "slug" field

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#18]
Scenario :  
1) Enter category name.
2) Whenever I am entering any category , same name is auto generating in "Slug" field.
3) But at the same time I am able to edit "Slug" field by giving another input and data is getting saved as well.

Expected result : "Slug" field should not be editable.

Note : kindly check once with BA before making the changes like "Slug" field should be editable or not?? 

![Normal entering category](https://user-images.githubusercontent.com/69690962/90308224-66bc5e80-defb-11ea-8245-f06b21a0f2af.png)

![able to edit slug field](https://user-images.githubusercontent.com/69690962/90308233-78056b00-defb-11ea-8a12-9f135785a54b.png)

**Comment by ameyranavade** [comment]
As per discussion with @pagumakwana slug should not be visible to user.. so Hide the text field.
