### ISSUE TITLE
Manage Category > Add category || Cover image browsing field

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#19]
Scenario :    

In "Upload service cover image" , I am able to browse and add all types of attachment like images, PDF's , .xlsx , MP3 file etc...

Expect result : 
1) Below browsing field, Kindly add specifications like it should accept only this particular file type images.
2) If admin is browsing images apart from mentioned specification then alert message should appear like "Please select valid file type"

![add specification of files](https://user-images.githubusercontent.com/69690962/90308642-b9e3e080-defe-11ea-8899-ff4565eb6867.png)

**Comment by ameyranavade** [comment]
Added File validation
