### ISSUE TITLE
Manage Category || Alignment and design issue of Action buttons

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#20]
Whichever action button are displaying, all are aligned differently and changes alignment  automatically when I search for any keyword.
Kindly design Table in way that whatever data I am adding and whichever button are there, it should be aligned in a single manner.

![alignment 2(1)](https://user-images.githubusercontent.com/69690962/90309032-43e17880-df02-11ea-90dd-3156dde96b81.png)
![alignment 2](https://user-images.githubusercontent.com/69690962/90309033-4643d280-df02-11ea-9e8b-5191c03e02b3.png)
![Action button design issue 1](https://user-images.githubusercontent.com/69690962/90309038-5196fe00-df02-11ea-8196-7ac82d6b8e0b.png)

**Comment by pagumakwana** [comment]
resolved
