### ISSUE TITLE
Manage Category || Action icons functionality issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#21]
Highlighted "icons" are not working in Action column.

Kindly check which one we are going to use..Those particular Icons or given "Edit" and "Delete" button.
And display only those icons or button which are required and remove other one.

Make sure whichever edit/Delete button or icons we are displaying should be functional.

![Highlighted icons are not working](https://user-images.githubusercontent.com/69690962/90309302-fe727a80-df04-11ea-8d74-e26fcbc27ed0.png)

**Comment by ameyranavade** [comment]
Made necessary changes also removed createdby column
