### ISSUE TITLE
Manage category || Issue while updating category

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#22]
Scenario :
1) Enter category name "testing 123"
2) Selected "Parent category" as "Bass house"
3) Select Category type and click on add button
4) Try to modify that added category and this time I have selected Parent category as "testing 123" (Category name which I had added)
5) Click on modify button.

Actual result :  I am able to select same category as  " Parent category " which I am trying to modify. And got successful modification message as well

Expected result : Admin should not be able to select same "parent category" which they are actually trying to modify. Alert message should appear like "Please select different Parent category"

PFA
![able to select same parent category which i have added](https://user-images.githubusercontent.com/69690962/90309795-2b289100-df09-11ea-9f3a-827a9998edd7.png)

**Comment by ameyranavade** [comment]
@pagumakwana please help.

**Comment by ameyranavade** [comment]
I think this situation will not be face as now bcous of duplicate name validation. @sangeetajad  please validate if still need to do something here.

**Comment by pagumakwana** [comment]
@ameyranavade Please remove slug text box from page. PLease call me for further discussion

**Comment by ameyranavade** [comment]
@pagumakwana removed slug.

**Comment by ameyranavade** [comment]
Made changes if you edit any category you wont find same category in parent category list during modify
