### ISSUE TITLE
Manage Service > Delete service || Alignment issue 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#24]
1) Go to Manage service 
2) Click on delete button of any service 
3) Confirmation pop up will appear

As highlighted in screenshot, kindly change alignment of cancel button and Yes button

![Delete button alignment issue](https://user-images.githubusercontent.com/69690962/90329727-da766e00-dfc4-11ea-86c0-f05ba18c9151.png)

**Comment by PallaviChapla** [comment]
Done
