### ISSUE TITLE
Manage service || Delete service functionality issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#25]
Scenario 

1) Go to manage service
2) Click on delete button of any service
3) Confirmation pop up will appear. Click on "Yes"

Actual result : When I click on "Yes" button, successful message is appearing like "Service deleted successfully" but on actual service is not getting deleted 

Expected result : After deleting any service , that should not be present in the list. Service should get deleted successfully.

**Comment by ameyranavade** [comment]
@PallaviChapla need popup for delete. please do needfull

**Comment by ameyranavade** [comment]
Made necessary changes but also has API side issue as even successfully deleted its again showing up in Get API. @pagumakwana  please check
