### ISSUE TITLE
Manage Service > Add Service functionality issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#26]
Scenario 

1) Go to Manage service > Add Service
2) Enter all the mandatory fields and add new service 

Actual result : Whenever I add new service, It gets replaced with earlier added service. and before added services are not showing in the list. only latest added one service is visible

Expected result : Whenever we add new service, it should be replaced with earlier added service.
And all the added services should be present in the list

**Comment by ameyranavade** [comment]
hello @sangeetajad I have checked the issue its from API side. @pagumakwana please do needfull

also i have added check for already exist flag. so duplicate name wont accept.

**Comment by ameyranavade** [comment]
Assign this to @pagumakwana

**Comment by ameyranavade** [comment]
https://edmapi.webdroids.in/api/Admin/ServiceManagement/Service


{"Ref_Service_ID":0,"Ref_Category_ID":"28","ServiceTitle":"testing_delete","Description":"delete","AliasName":"testing_delete","Price":"55","PriceWithProjectFiles":"100","BigImageUrl":null,"ThumbnailImageUrl":null,"ServiceVideoUrl":null,"ProjectFilesUrl":null,"Revision":"10","DeliveryDate":"2020-09-30","CreatedName":"amey ranavade","FAQDetails":[{"Questions":"delete","Answer":"delete"}],"FileUrls":[{"Ref_ID":0,"Ref_File_ID":0,"FileName":"Screenshot (11)_2020-08-23-10-26-19.png","FilePath":"/FileStorage/Service/Screenshot (11)_2020-08-23-10-26-19.png","FileType":"image/png","FileExtension":".png","FileSize":117458,"ModuleName":"Service","FileIdentifier":"BigImageUrl","DisplayOrder":1,"Flag":null,"Ref_User_ID":0,"CreatedDateTime":null,"CreatedBy":null,"CreatedName":null,"UpdatedDateTime":null,"UpdatedBy":null,"UpdatedName":null,"IsActive":null,"IsDeleted":null,"FileUrls":null,"MetaTitle":null,"MetaKeywords":null,"MetaDescription":null},{"Ref_ID":0,"Ref_File_ID":0,"FileName":"Screenshot (9)_2020-08-23-10-26-19.png","FilePath":"/FileStorage/Service/Screenshot (9)_2020-08-23-10-26-19.png","FileType":"image/png","FileExtension":".png","FileSize":395674,"ModuleName":"Service","FileIdentifier":"BigImageUrl","DisplayOrder":2,"Flag":null,"Ref_User_ID":0,"CreatedDateTime":null,"CreatedBy":null,"CreatedName":null,"UpdatedDateTime":null,"UpdatedBy":null,"UpdatedName":null,"IsActive":null,"IsDeleted":null,"FileUrls":null,"MetaTitle":null,"MetaKeywords":null,"MetaDescription":null},{"Ref_ID":0,"Ref_File_ID":0,"FileName":"Screenshot (10)_2020-08-23-10-26-19.png","FilePath":"/FileStorage/Service/Screenshot (10)_2020-08-23-10-26-19.png","FileType":"image/png","FileExtension":".png","FileSize":313241,"ModuleName":"Service","FileIdentifier":"BigImageUrl","DisplayOrder":3,"Flag":null,"Ref_User_ID":0,"CreatedDateTime":null,"CreatedBy":null,"CreatedName":null,"UpdatedDateTime":null,"UpdatedBy":null,"UpdatedName":null,"IsActive":null,"IsDeleted":null,"FileUrls":null,"MetaTitle":null,"MetaKeywords":null,"MetaDescription":null},{"Ref_ID":0,"Ref_File_ID":0,"FileName":"file_example_MP4_480_1_5MG_2020-08-23-10-26-22.mp4","FilePath":"/FileStorage/ServiceVideo/file_example_MP4_480_1_5MG_2020-08-23-10-26-22.mp4","FileType":"video/mp4","FileExtension":".mp4","FileSize":1570024,"ModuleName":"ServiceVideo","FileIdentifier":"ServiceVideoUrl","DisplayOrder":1,"Flag":null,"Ref_User_ID":0,"CreatedDateTime":null,"CreatedBy":null,"CreatedName":null,"UpdatedDateTime":null,"UpdatedBy":null,"UpdatedName":null,"IsActive":null,"IsDeleted":null,"FileUrls":null,"MetaTitle":null,"MetaKeywords":null,"MetaDescription":null}],"MetaTitle":"","MetaKeywords":"","MetaDescription":"","Flag":"ADDSERVICE","Ref_User_ID":"5"}


ExceptionMessage: "Cannot insert the value NULL into column 'Ref_ObjectMapping_ID', table 'DB_A4A30B_EDM.dbo.ProducerObjectMapping'; column does not allow nulls. INSERT fails."
ExceptionType: "System.Data.SqlClient.SqlException"
Message: "An error has occurred."

500 Error please check

**Comment by ameyranavade** [comment]
![image](https://user-images.githubusercontent.com/47138480/90984750-a981d480-e594-11ea-9b94-b3d6c34c963e.png)

Still even 500 error the service is showing in the grid window but file was not visible
