### ISSUE TITLE
Manage category || Textual issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#27]
1) Navigate to Manage category 
2) As highlighted in screenshot

Kindly replace "CategoryName" with "Category Name" , "CreatedBy" with "Created By"

![textual issue in category](https://user-images.githubusercontent.com/69690962/90330022-4eb21100-dfc7-11ea-81be-199eaf87eb51.png)

**Comment by ameyranavade** [comment]
Made necessary changes.
