### ISSUE TITLE
Manage Service || Textual issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#29]
Navigate to "Manage Service"

As highlighted in screenshot,
Kindly replace "ServiceTitle" with "Service Title" , "PriceWithProjectFiles" with "Price With Project Files"

PFA

![Texual issue in service](https://user-images.githubusercontent.com/69690962/90330249-e82df280-dfc8-11ea-98d7-903a409f1b01.png)

**Comment by ameyranavade** [comment]
Made neccessary changes
