### ISSUE TITLE
Manage Category || Duplicate category name issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#30]
Scenario 1 :  

1) I have added New category name "Testing 123" in "Beats - category type" and it gets added successfully.
2) Now again I have added same category name (i.e Testing 123" in same category type "Beats"
3) Click on add button, no response is coming.

Expected Result : When User add Same category name in same category type then Alert message should appear like "Category name" is already exists.

Scenario 2 :  
1) Now I have added category name "Testing 123" in different Category type like "Bass"
3) Click on add button, No response is coming neither category is getting added.

Expected result :   
When user adds same category name which is already existed in the system , and select different Category type then Category name should get added successfully.

**Comment by ameyranavade** [comment]
Added Duplicate check validation.
