### ISSUE TITLE
Manage Service > Add service || Upload video field issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#35]
Manage Service > Add service 

 As highlighted in screenshot for "Upload service video" field :   
1) Video field is accepting all type of files like PDF, xlsx , PNG, JPEG, MP3  etc.

Expected result : It a video browsing field hence It should accept only MP4 or any other video format , Kindly discuss with BA and define the file type and apart from that it should not accept other file format

2) In note : we have mentioned that it takes attachment like .JPG , .PNG 

Expected result : Kindly remove that Note and define proper file format which That field is going to accept

PFA

![Upload video field](https://user-images.githubusercontent.com/69690962/90379350-407ff580-e098-11ea-8575-7dc0798316be.png)

**Comment by ameyranavade** [comment]
Added file validation
