### ISSUE TITLE
Manage Service > Add Service > Upload service cover image 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#36]
Manage Service > Add Service > Upload service cover image 

1) I am able to browse all type of image in "Cover image" like PDF, MP3, MP4, xlsx , which are not valid.

Expected result : user should be able to accept only valid image file format like jpg, png, jpeg.
Provide proper validation if user is browsing invalid file format like "Please select valid file"

![Upload service cover](https://user-images.githubusercontent.com/69690962/90380822-30691580-e09a-11ea-9393-6d551297c2e7.png)

**Comment by ameyranavade** [comment]
Added file validation
