### ISSUE TITLE
Manage service > Add Service || Extra video and Cover images are appearing 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#38]
Manage service > Add Service

While adding Service I had uploaded one "service video" and one "service cover  image" 

Actual result :  
1) On service list thumbnail image , wrong image was visible which I had not uploaded
2) When try to edit that service, On modify page I could see that extra service video and service cover images are visible which I had not selected while adding that particular service.

Expected result :   

1) Only those Video and Cover file should visible on modify service page which I had uploaded while adding service.
2) Thumbnail image should be same as I had uploaded while adding service

Please refer added screenshots

![Before adding](https://user-images.githubusercontent.com/69690962/90417438-5362ec00-e0d1-11ea-9640-9b2d4e880c18.png)

![Wrong thumb nail image](https://user-images.githubusercontent.com/69690962/90417493-670e5280-e0d1-11ea-972a-a9a903f57507.png)

![After 1](https://user-images.githubusercontent.com/69690962/90417507-6e356080-e0d1-11ea-814e-7ea70a38236b.png)

![After 2](https://user-images.githubusercontent.com/69690962/90417533-75f50500-e0d1-11ea-9922-1701f8fe9326.png)

**Comment by ameyranavade** [comment]
Service issue solved
