### ISSUE TITLE
Manage service > Edit Service || 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#39]
1) Try to edit any added service , modify few changes and Click on "Modify button"

Actual result : When I modify any service , at right hand corner "Service updated successfully" pop up is appearing and with that "Thank you" pop up is also appearing.

Kindly remove that "thank you" pop up and keep only one successfully message which is appearing at right hand corner

**Comment by ameyranavade** [comment]
Removed popup
