### ISSUE TITLE
Manage Service >Add Service || Mandatory field issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#41]
As highlighted in screenshot , I have checked those field which are mandatory.
Kindly add * asterisk mark before all the mandatory field.

**Note : Kindly discuss with  Pragnesh or with BA first, before making this changes.**

PFA

![Mandatory field](https://user-images.githubusercontent.com/69690962/90420245-5364eb00-e0d5-11ea-9f1d-420c183c6de9.png)

**Comment by pagumakwana** [comment]
I have resolved and committed this issue
