### ISSUE TITLE
Add Tracks module || Track beats per minutes field

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#46]
Kindly set one limit for "Tracks beats per minutes" fields as it is taking "N" number of digits.

Set any limit and accordingly ask developer to  restrict it.

PFA

![beats per minute](https://user-images.githubusercontent.com/69690962/90427359-0c302780-e0e0-11ea-9afe-5e2bc917fd49.png)

**Comment by pagumakwana** [comment]
![WhatsApp Image 2020-08-24 at 9 59 46 PM](https://user-images.githubusercontent.com/14257643/91071201-879c5680-e655-11ea-8ba8-e778ddfbaf3b.jpeg)
As per the comments field is required to be open field. so this will not change now

**Comment by smsan80** [comment]
Done
