### ISSUE TITLE
Add Tracks module || Key field - Check input validation

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#48]
Add Track module :  

In "Key Field" as of now no character limit is given. It is taking "N" numbers of digits, characters and special character.

Kindly define some character limit and also check if it should take all type of special character or not?? If not then which special characters is should take  ,define that as well.

Accordingly ask developer to implement it.

PFA

![Key field specifications ](https://user-images.githubusercontent.com/69690962/90429230-eb1d0600-e0e2-11ea-9a87-d0c2206ab17b.png)

**Comment by pagumakwana** [comment]
![WhatsApp Image 2020-08-24 at 9 59 46 PM](https://user-images.githubusercontent.com/14257643/91071524-ebbf1a80-e655-11ea-8795-8cdcb8ae59aa.jpeg)
As per previous comments there should be open text box we can not change this option again. @smsan80  only restrict special character except '-' & ' '

**Comment by smsan80** [comment]
Done

**Comment by sangeetajad** [comment]
Key field is still taking all the special characters. Kindly restrict all the special character except '-' & ' '

![Special chracter issue](https://user-images.githubusercontent.com/69690962/92618073-97669c80-f2dd-11ea-8545-409d60656b67.png)

**Comment by smsan80** [comment]
Done
