### ISSUE TITLE
Modify tracks || Modify Beats || Track cover image issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#51]
From added list of tracks :

1) Click on "edit" button. 
2) In "Upload track cover image" field , file path should not be displaying instead of that uploaded file image will be visible with remove button.

You can refer Category module for this functionality and also discuss with Pragnesh before doing this changes.

**_NOTE : Do the same changes in "ADD BEATS" module as well_**

PFA
![On modify field](https://user-images.githubusercontent.com/69690962/90545471-5380eb80-e1a6-11ea-87eb-4dfc4172958d.png)

**Comment by smsan80** [comment]
I was done as per wireframe. Please check with Pragnesh
