### ISSUE TITLE
Add Tracks || Add Beats || Global issue - Validation pop up message functionality

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#52]
Global issue :   

Whenever we browse any invalid file , pop up is appearing at the top. Remove that pop up and validation message should appear near that particular browsing field.

Do the changes in both module (Add tracks, Add Beats)

PFA

![Invalid file formate ](https://user-images.githubusercontent.com/69690962/90545948-094c3a00-e1a7-11ea-8f66-0a4cfc0dcbec.png)

![valid file validation text](https://user-images.githubusercontent.com/69690962/90546009-1cf7a080-e1a7-11ea-815c-352c43de59e1.png)

**Comment by smsan80** [comment]
Done
