### ISSUE TITLE
Sign up page || I agree to receive email Check box functionality

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#63]
As highlighted in screenshot,

I am unable select or De-select "I agree to receive email" field.

Kindly Discuss with BA or Pragnesh ,  what is the functionality of that field and according implement it. 

PFA

![I agree to receive email check box](https://user-images.githubusercontent.com/69690962/91078359-2463f180-e660-11ea-8b8d-1b2a8b534e2e.png)

**Comment by rawshan-more** [comment]
Issue resolved.
