### ISSUE TITLE
Add Service || Select revision field issue 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#66]
Scenario :  
1) Enter all  the mandatory fields.
2) In " Select revision"  I am selecting any number from the given list (for eg. 6) and adds new service.
3) When check that in Service list , i could see that "Select revision" count becomes "1" automatically. (Ideally it should be the same count which I had selected i.e "6")
4) Infact when I try to edit service that time as well same issue  is coming. Whatever count I select , It is taking "1" only.

Expected result : While adding or modifying service "Select revision" count should be not be changed to "1"  and it should display only that count which I had selected .

PFA

![Before adding service](https://user-images.githubusercontent.com/69690962/91735071-642f5980-ebc9-11ea-80dd-f20bd62d051b.png)

![after adding service](https://user-images.githubusercontent.com/69690962/91735105-714c4880-ebc9-11ea-9cc1-7aa262361679.png)

**Comment by ameyranavade** [comment]
Bheem please check revision field it always set to 1

Request URL: http://edmapi.webdroids.in/api/Admin/ServiceManagement/Service

{"Ref_Service_ID":2,"Ref_Category_ID":5,"AliasName":"artist-branding","ServiceTitle":"Artist Branding","Description":"Branding","Price":22,"PriceWithProjectFiles":23,"Revision":"4","DeliveryDate":"2020-09-09","FAQDetails":[{"Questions":"Q1","Answer":"A1"}],"FileManager":[],"Flag":"MODIFYSERVICE","Ref_User_ID":"5","CreatedDateTime":"2020-09-10T17:47:10.16","CreatedBy":1,"CreatedName":"amey ranavade","UpdatedDateTime":null,"UpdatedBy":null,"UpdatedName":null,"IsActive":true,"IsDeleted":false,"FileUrls":null,"MetaTitle":"","MetaKeywords":"","MetaDescription":""}

![image](https://user-images.githubusercontent.com/47138480/101861139-61afa900-3b95-11eb-884f-fc1238cb6587.png)
