### ISSUE TITLE
Add Tracks || Textual issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#67]
Add Tracks

1) In Beats per minutes field , Kindly replace "BMP" with "BPM"
2) Replace error message "Amount limit upto 300" with "BPM limit upto 300"

PFA

![BPM limit upto 300](https://user-images.githubusercontent.com/69690962/91876970-fc494380-ec9a-11ea-8183-4fe9c23d5e1a.png)

![BPM textual issue](https://user-images.githubusercontent.com/69690962/91876998-08350580-ec9b-11ea-88ee-4bbfee90be68.png)

**Comment by smsan80** [comment]
Done
