### ISSUE TITLE
Tracks || Beats Modules - Textual issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#68]
Tracks || Beats Modules

As highlighted in screenshots, Kindly replace "Track Approval" and "Beat Approval"  with "ACTIONS"

PFA

![Action ](https://user-images.githubusercontent.com/69690962/91880894-539ce300-ec9e-11ea-9a39-8b3a07ddcba4.png)

![Beat approval with action](https://user-images.githubusercontent.com/69690962/91880937-644d5900-ec9e-11ea-8d1d-53aabe7c252d.png)

**Comment by smsan80** [comment]
Done
