### ISSUE TITLE
Beats || Tracks module - Enhancement 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#69]
Beats || Tracks modules

1) Kindly remove Edit, Delete, View button from both the modules and Add  icons of "Edit" and "Delete" . (Take reference from "Category" module)

PFA

![Action buttons](https://user-images.githubusercontent.com/69690962/91882436-93fd6080-eca0-11ea-80c3-77a2a35a66d1.png)

![Actions button 2](https://user-images.githubusercontent.com/69690962/91882450-9c559b80-eca0-11ea-8f13-b9f2e9ea5fe2.png)

**Comment by smsan80** [comment]
Done
