### ISSUE TITLE
Service module | Multiple thumbnail Image preview layout

### ISSUE THREAD

**Issue by pagumakwana** [pagumakwana/repo_edm#7]
Please align thumbnail preview from vertical to horizontal and provide appropriate height and width. Kindly connect amy in case of any query.
![serviceimagepreview](https://user-images.githubusercontent.com/14257643/88711288-987ca980-d135-11ea-935f-0ef1b2363444.jpeg)

**Comment by PallaviChapla** [comment]
Please provide me design for this issue !! @pagumakwana @Eden310 ??

**Comment by PallaviChapla** [comment]
Done
