### ISSUE TITLE
Beats module - Functionality and textual issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#70]
Scenario :

1) Add New beat.
2) After adding beat, on Beat list page "Approve" , "Reject" button will be displayed. Click on "Reject"
3) When you click on "Reject" button, it will ask for reason then I enter any reason and again click on "Reject"
4) That time pop up message is appearing at the top, kindly remove that and in the  middle off the page one Pop up text should appear like "Do You want to Reject? " with "CANCEL" and "YES" button.  (Regarding this design you can discuss with Pragnesh like how that pop up should appear)

5) Once you click on "OK" reject , It redirect you to page beat list page where it is showing "No records found" which is wrong.
Because I need to refresh to check the updated list. (Expected result - After rejecting , directly list of BEATS should appear. User should not need to refresh the page.

PFA

![Reject ](https://user-images.githubusercontent.com/69690962/91887646-ad0a0f80-eca8-11ea-9117-62e083bf9c8a.png)

![reject confirmation](https://user-images.githubusercontent.com/69690962/91887669-b4c9b400-eca8-11ea-8afa-a1696e668844.png)

![No records found](https://user-images.githubusercontent.com/69690962/91887716-c448fd00-eca8-11ea-82ed-2f62a39f788d.png)

**Comment by smsan80** [comment]
close
