### ISSUE TITLE
Beat Module - APPROVE functionality issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#72]
Scenario :   

1) Add new beat.
2) After adding new beat, "Approve" and "Reject" button will be displayed.
3) Click on "Approve " button.
4) When we click on approve button, pop is appearing at the top.
Kindly remove that pop up and show Message in the middle of the page "Beat approved successfully"

5) After approval , "No records found" is coming, which is wrong because I need to refresh page to check updated data.
(Expected result : No Record found should not be visible and directly main beat list page be visible. User should not have to refresh page)

PFA

![approve](https://user-images.githubusercontent.com/69690962/91889182-0e32e280-ecab-11ea-80fc-2bd8746f8f07.png)

**Comment by smsan80** [comment]
close
