### ISSUE TITLE
Add Beats || Add tracks || Textual issue and Close button functionality implementation 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#73]
Scenario 1 :  
1) Enter new beat.
2) After entering new beat Thank you message is appearing , in that pop up kindly add "Close button icon" so that user close that pop up because currently that pop is not getting closed automatically even after few second and I need to Back that page.
(Do the same changes when we edit any beat)

Scenario 2 :  
1) After adding new beat , two options are appearing "Approve" and "rejected"
2) Click on "Reject". After rejecting beat , successful message is appearing like "Beatrejcted successfully" . There is no space between the text, hence kindly replace it with "Beat Rejected Successfully"

Scenario 3 :  
1) After adding new beat , two options are appearing "Approve" and "rejected"
2) Click on "Approve". After rejecting beat , successful message is appearing like "Beatapproved successfully" . There is no space between the text, hence kindly replace it with "Beat Approved Successfully"

**Note - Above mentioned 3 scenarios are applicable for "TRACK" module as well. Hence kindly do the same changes in "tracks" and "Beats" both modules.**

**Comment by smsan80** [comment]
Done
