### ISSUE TITLE
Category || Add and Delete category issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#75]
Scenario : 

1) Enter all the mandatory fields and Click on add button

Actual result : " Category added successfully" message is not appearing

2) Now try to delete any Category.

Actual result : When I delete any category then " Something went wrong" message is appearing. Also CATEGORY is not getting deleted.

Expected result : Category should gets deleted successfully with " Category Deleted successfully" message.

**Comment by ameyranavade** [comment]
@Bheem please check Delete not happening

Request URL: http://edmapi.webdroids.in/api/Admin/MasterManagement/Category

{"Flag":"DELETECATEGORY","Ref_User_ID":"5","Ref_Category_ID":9,"Ref_Parent_ID":1,"CategoryName":"test category 11-123","Description":"123","CreatedName":"amey ranavade","AliasName":"test-category-11-123"}

![image](https://user-images.githubusercontent.com/47138480/101860727-67f15580-3b94-11eb-9f9b-64e9030ddb41.png)

**Comment by ameyranavade** [comment]
Bheem please check Add get 500 error but category gets added in listing page

Request URL: http://edmapi.webdroids.in/api/Admin/MasterManagement/Category

{"Flag":"ADDCATEGORY","Ref_Parent_ID":"","Ref_Category_ID":"","CategoryName":"dummy category add","AliasName":"dummy-category-add","Description":"desc","CategoryUseBy":"1","FileUrls":[],"Ref_User_ID":"5","CreatedName":"amey ranavade","MetaTitle":"1","MetaKeywords":"1","MetaDescription":"1"}

![image](https://user-images.githubusercontent.com/47138480/101860890-d3d3be00-3b94-11eb-934f-cb2b9d67b159.png)

**Comment by ameyranavade** [comment]
@PallaviChapla Point no. 2 can you please check with Datepicker design.

**Comment by RvThothwal** [comment]
Please replace  FileUrls":[], to FileManager":[] 

{"Ref_Category_ID":9,"Ref_Parent_ID":1,"CategoryName":"TEST 1312","AliasName":"test-1312","CategoryUseBy":0,"Description":"TESTINGss","MetaTitle":"","MetaKeywords":"","MetaDescription":"","IsActive":true,"Ref_User_ID":"5","FileManager":[],"Flag":"MODIFYCATEGORY","CreatedName":"amey ranavade"}

**Comment by ameyranavade** [comment]
Solved
