### ISSUE TITLE
Beats Module || Issue in modify beats

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#76]
Scenario :  

1) I have added beats cover image and audio track is not visible in the "Beat List page".
2) Now Try to edit any Approved or Rejected beats , there I can see that Beats cover image, and other audio files which i had uploaded are missing. It is asking me again to browse all the files.

Refer attached screenshots.

Expected result :   
1) Already added beats cover image and audio track should be visible and should be able play pause on Beat list page
2) When I try to edit any beat that time, already browsed cover Image and Audio files should be present in the field and if user wants to modify those selected files then they will have to remove those files and upload new one. Also modified changes should also be reflected in the module as well as User side.

![already browed files ar not available when I modify beats](https://user-images.githubusercontent.com/69690962/96464261-3b305a00-1245-11eb-9ca6-0190838e7b8c.png)

![Beats images and audio is missing](https://user-images.githubusercontent.com/69690962/96464303-471c1c00-1245-11eb-9e31-ec6629f77117.png)

**Comment by smsan80** [comment]
Done
