### ISSUE TITLE
Beats module ||  Tracks module || Rejected reason is not showing

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#77]
Scenario :  

1) In Beats list page , Click on "read more" hyperlink of Any rejected beat. As highlighted in screenshot , rejected reason is showing dash "-"

Same issue is Track module as well. Kindly fix in both the modules.

PFA

![Click on read more of rejected beat](https://user-images.githubusercontent.com/69690962/96465202-5059b880-1246-11eb-9fbb-5a5d0c2a3783.png)

![rejected reason is missing](https://user-images.githubusercontent.com/69690962/96465308-71220e00-1246-11eb-8a5c-b712a1eadf87.png)

**Comment by smsan80** [comment]
Done
