### ISSUE TITLE
Track module || Issue at Modify Tracks page

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#78]
Scenario :

1) I have added track cover image and audio track is not visible in the "Track List page".
2) Now Try to edit any Approved or Rejected Tracks , there I can see that track cover image, and other audio files which i had uploaded are missing. It is asking me again to browse all the files.
Refer attached screenshots.

Expected result :

1) Already added tracks cover image and audio track should be visible and should be able play pause on Track list page
2) When I try to edit any Track that time, already browsed cover Image and Audio files should be present in the field and if user wants to modify those selected files then they will have to remove those files and upload new one. Also modified changes should also be reflected in the module as well as User side.

![file path are missing in modify track page](https://user-images.githubusercontent.com/69690962/96467878-0aeaba80-1249-11eb-8299-1b32884bffea.png)

![Track cover image and audio is missing](https://user-images.githubusercontent.com/69690962/96467905-14742280-1249-11eb-8e0d-8375ad5aaf4f.png)

**Comment by smsan80** [comment]
Done
