### ISSUE TITLE
Front end - Tracks - alignment issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#80]
As highlighted in screenshot,
1) When I click on Any track to view its details, its alignment changes.
2) Same is for producer profiles as well. 
3) Click on store tab of the frontend, there select TRACK. List of tracks will appear ..try to view track from that page page as I can see alignment issue.

Check  attached before and After images.

![Before alignment](https://user-images.githubusercontent.com/69690962/96490347-4f348580-125e-11eb-8810-01c3b0551737.png)

![alignment changes after viewing track](https://user-images.githubusercontent.com/69690962/96490373-56f42a00-125e-11eb-90e0-b03749a730ac.png)
![producer profile](https://user-images.githubusercontent.com/69690962/96490673-c23dfc00-125e-11eb-8489-a17e6c4d8e40.png)

![from store module as well](https://user-images.githubusercontent.com/69690962/96581371-58bdfc00-12f7-11eb-9de9-0b54b42be6da.png)

**Comment by PallaviChapla** [comment]
Done
