### ISSUE TITLE
Frontend Beats || Aligment issue 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#83]
Scenario :   

1) Click on "Store" tab of user side
2) Select "Beat" . It will redirect you to beat list page.
3) Click on any beat, to view its details. It will redirect you to Related beats page. There as highlighted in screenshot, Alignment is not proper. It changes automatically

PFA
![ALIGNMENT ISSUE IN BEATS](https://user-images.githubusercontent.com/69690962/96747227-a7e25a80-13e5-11eb-8c6e-6a08772efdd0.png)

**Comment by PallaviChapla** [comment]
Done
