### ISSUE TITLE
Front End Beats || Inconsistency in Beats Details

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#84]
Scenario :  
1) Click on STORE tab
2) Select "Beats" . It will redirect you to beats list
3) Click on any beat to check its full details.

As highlighted in screenshots, for some of the beats ,  Related beats shows "No records found" . Sometimes beat details are missing. Infect even for newly added beats as well details are missing.
Sometimes it shows all the details. In short there is no consistency in displaying BEAT details.
Refer below images.

![beat deatils are missing](https://user-images.githubusercontent.com/69690962/96750265-62c02780-13e9-11eb-9b83-38d490dcd8dc.png)

![no records found in beats](https://user-images.githubusercontent.com/69690962/96750320-72d80700-13e9-11eb-9e7f-baecdc5cecf1.png)

![sometimes related beats are there](https://user-images.githubusercontent.com/69690962/96750402-871c0400-13e9-11eb-9584-a20fc2b2e810.png)

**Comment by smsan80** [comment]
Done
