### ISSUE TITLE
Service Module || Service Cover Image modification issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#85]
Scenario :  
1) I have added one Service also browsed Service cover image.
2) Now Try to modify added service. This time remove previously added service cover image and browse new image and click on modify button.
3) Service gets modified successfully but when I check that service details,  I can see in Service cover image field there still 1st added image is visible. Infect at Service list page as well old image is visible.  Refer below screenshots.

Expected result : After updating  cover image only that newly browsed image should be visible in Modify page as well at Service list page.

PFA

![2 images are visible](https://user-images.githubusercontent.com/69690962/96894909-89de2e00-14a9-11eb-95fa-7209d9fb660a.png)

![primary image is showing](https://user-images.githubusercontent.com/69690962/96895008-9793b380-14a9-11eb-8d1b-c72db37b3605.png)

![actual image after modification](https://user-images.githubusercontent.com/69690962/96895075-a37f7580-14a9-11eb-90df-cf220a896b26.png)

**Comment by ameyranavade** [comment]
I have been told by @bheem to display the first Image. As I get list of array of images and according to that bheem sends the data from backend

**Comment by RvThothwal** [comment]
Dude she's removing the last one in that case u need to call file remove api.
