### ISSUE TITLE
Frontend || Beats and Tracks page

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#86]
Scenario :
1) Click on "Store" menu
2) Select TRACKS. As highlighted in screenshot, Genre(Category) cover images are not displaying properly. 
3) Same is for BEATS page as well. 

Make sure whichever Genre (category) I have added should be visible at front end including its cover image.

PFA

![on beats page as well](https://user-images.githubusercontent.com/69690962/97025663-050d1600-1576-11eb-88f1-216045373a73.png)

![Genre images are not loading](https://user-images.githubusercontent.com/69690962/97025755-2110b780-1576-11eb-9531-089fd237eaa4.png)

**Comment by smsan80** [comment]
pls first check category list image. if there are images show properly then images will show here.
