### ISSUE TITLE
Track Module || Modify Track page - Unable remove and browse  .MIDI File

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#87]
Scenario :  
1) On Track list page, Click on Edit button to modify and Track
2) Now remove .midi file.

Actual result : I am unable to remove .midi file also unable to browse new .midi file.

Expected result : Admin should be able to remove and browse new .midi file while modifying track.

PFA

![unable to remove midi file](https://user-images.githubusercontent.com/69690962/97589127-30cf4680-1a23-11eb-9093-be003e6de0c8.png)

**Comment by smsan80** [comment]
Done
