### ISSUE TITLE
Category Module || Textual issue 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#88]
On Add Category page :  

As highlighted in screenshot , Kindly replace " Upload Service Cover Image" with " Upload Category Cover Image "

PFA

![replace with Category cover image](https://user-images.githubusercontent.com/69690962/97591951-2498b880-1a26-11eb-8288-6472e1a413d5.png)

**Comment by ameyranavade** [comment]
Done
