### ISSUE TITLE
Profile Pic icon issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#94]
As highlighted in screenshot,
Profile pic icon image is broken

1) If user has not uploaded profile pic then default background should be visible
2) If user has uploaded profile pic then that image should be visible

PFA
![profile pic icon is broken](https://user-images.githubusercontent.com/69690962/102011858-02a48c80-3d6d-11eb-87e2-33fd39d24a4f.png)

**Comment by PallaviChapla** [comment]
@pagumakwana If the user does not upload the profile picture, then hide <img> tag. Then the issue will be solved.

**Comment by pagumakwana** [comment]
resolved
