### ISSUE TITLE
404 ERROR Issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#96]
Whenever I click on refresh button , it shows 404 error
It doesn't matter on what module or at which page I am including login page, user side, admin side. It is happening at every refresh button click

PFA

![404 when I click on back to sign in](https://user-images.githubusercontent.com/69690962/102012327-c161ac00-3d6f-11eb-84e9-8ca89ec7fb37.png)

**Comment by pagumakwana** [comment]
resolved
