### ISSUE TITLE
Category || Filter by Genre type - functionality issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#97]
Scenario :   

1) Click on  CATEGORY module
2) Click on Filter by genre type option to filter out list
List is not getting updated properly as per the selected filter. Also count is not displaying properly as highlighted in screenshots

For eg. 
- click on TRACK filter , I could see 2 entries but count shows ( 1 of 8 entries)
- click on NEWS , there no records  are available still showing (1 of 8 entries)
- click on ALL , all the category list should appear but blank data is appearing

ETC.

Expected result : All the filter by genre type should work properly as per the selected type
Also entry count should get updated correctly. Like count should match with the data list

PFA

![1 of 8 even though 2 entries are there](https://user-images.githubusercontent.com/69690962/102012769-4c43a600-3d72-11eb-9d5f-dab4d358d277.png)
![on clicking on news ](https://user-images.githubusercontent.com/69690962/102012788-5c5b8580-3d72-11eb-9041-3f5d8c0b6388.png)
![click on all filter](https://user-images.githubusercontent.com/69690962/102012803-69787480-3d72-11eb-912b-d3a50cb6e660.png)

**Comment by ameyranavade** [comment]
Solved with #106
