### ISSUE TITLE
Category module || Category image issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#99]
Scenario :  

1) I have entered all the mandatory fields also added category cover image and added new category called "TEST 1312"
2) When I check on category list page , there selected category cover image is not visible 
3) Now click on edit button, there also I can see that there as well browsed image is not present
4) Also replace text " Upload service cover image" with "Upload category cover image"

PFA

![already browsed image is not visible](https://user-images.githubusercontent.com/69690962/102014822-0391ea00-3d7e-11eb-88c3-1f169ee1e31e.png)
![Newly added category image is missing](https://user-images.githubusercontent.com/69690962/102014831-11476f80-3d7e-11eb-8d37-2588ce5c9b22.png)

**Comment by ameyranavade** [comment]
![image](https://user-images.githubusercontent.com/47138480/103141159-2fb25100-4716-11eb-97aa-a10fbfe946cf.png)
@RvThothwal Please check image is not available at the location

**Comment by RvThothwal** [comment]
Pragensh has changed the server and forgot to move images on new server.
